### ISSUE TITLE
Enhancement: library/CSS loaded in header globally

### ISSUE THREAD

**Issue by cybeardjm** [stefanbohacek/fediverse-embeds-wordpress-plugin#25]
Hi,
Just noticed that the plugin's library & CSS are loaded on everywhere on the site...
- ftf-fediverse-embeds-frontend-styles
/wp-content/plugins/fediverse-embeds/includes/../dist/css/styles-bs.min.css 
- ftf-fediverse-embeds-frontend-js
/wp-content/plugins/fediverse-embeds/includes/../dist/js/scripts.js 

in the header.
Would it be possible to:
- move them to the footer?
or
- load them only on pages that contain an embedded Fediverse post? (prefered)

**Comment by stefanbohacek** [comment]
@cybeardjm It does make sense to limit loading the JS/CSS only when an embed is on the page, good call.

The tricky part here is that you can really embed a post on any page, not just a post/page. For example, here's a [tag page on my website](https://stefanbohacek.com/tag/fediverse/), which shows the tag description, and could easily include an embedded post.

I am going to need to look into the performance trade-offs in terms of necessary database queries. 

In the meantime, I checked one of your sites and I do see the JS loaded in the footer, as it should, since I am registering the script to be in the footer. Plus, I am also using the [defer script tag attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#defer), so the impact should really be minimal.

As for the CSS file, including it outside of the `head` element is not really commonly done, see:

- https://stackoverflow.com/questions/18392418/html-css-put-link-tag-outside-of-the-head	
- https://stackoverflow.com/questions/17781459/bad-consequences-of-linking-css-external-stylesheet-outside-of-head

**Comment by cybeardjm** [comment]
Been playing with various cache plugins (with gzip + other defer/swap techniques) and speed-testing platforms, this is why I've suggested this, as these CS/JS appear in most "complaints"... If it's possible, would be a "+".

**Comment by stefanbohacek** [comment]
Sure, that makes sense.

On a side note, I will add that the plugin still provides a [huge performance boost](https://stefanbohacek.com/project/wordpress-plugin-for-fediverse-embeds/#performance) compared to the default embed method, at least for Mastodon.

Either way, I'll definitely look into this some more. Thank you for bringing this up!

**Comment by stefanbohacek** [comment]
@cybeardjm Yes, adding an option to customize the behavior and let the user decide makes a lot of sense. Thank you for the suggestion!

**Comment by stefanbohacek** [comment]
Fixed in https://github.com/stefanbohacek/fediverse-embeds-wordpress-plugin/commit/932f2ab0393ed750405334c073b71430439bff1a and https://github.com/stefanbohacek/fediverse-embeds-wordpress-plugin/commit/91ff2db2497cd5e5f5024682107d287924697006.
